import {authReducer} from "./auth-reducer";

describe('auth reducer', () => {
    it('should return the initial state', () => {
        expect(authReducer(undefined, {} as any)).toEqual({
            authChecked: false,
            loggedIn: !!localStorage.getItem("accessToken"),
            isResetPasswordAvailable: false,
            registrationRequest: false,
            registrationFailed: false,
            currentLogin: "",
            currentName: "",
            authorizationRequest: false,
            authorizationFailed: false,
            accessToken: null,
            getUserInfoRequest: false,
            getUserInfoFailed: false,
            updateUserInfoRequest: false,
            updateUserInfoFailed: false,
            logoutRequest: false,
            logoutFailed: false,
            resetPasswordRequest: false,
            resetPasswordFailed: false,
            recoveryCodeRequest: false,
            recoveryCodeFailed: false,
            refreshTokenRequest: false,
            refreshTokenFailed: false,
            refreshTokenSuccess: false,
        })
    })

    it('should handle REGISTRATION_REQUEST', () => {
        expect(authReducer(undefined, {type: "REGISTRATION_REQUEST"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: true,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })

    it('should handle REGISTRATION_SUCCESS', () => {
        expect(authReducer(undefined, {
            type: "REGISTRATION_SUCCESS",
            email: "test",
            name: "test"
        })).toEqual({
            authChecked: true,
            loggedIn: true,
            isResetPasswordAvailable: false,
            registrationRequest: false,
            registrationFailed: false,
            currentLogin: "test",
            currentName: "test",
            authorizationRequest: false,
            authorizationFailed: false,
            accessToken: null,
            getUserInfoRequest: false,
            getUserInfoFailed: false,
            updateUserInfoRequest: false,
            updateUserInfoFailed: false,
            logoutRequest: false,
            logoutFailed: false,
            resetPasswordRequest: false,
            resetPasswordFailed: false,
            recoveryCodeRequest: false,
            recoveryCodeFailed: false,
            refreshTokenRequest: false,
            refreshTokenFailed: false,
            refreshTokenSuccess: false,
        })
    })

    it('should handle REGISTRATION_FAILED', () => {
        expect(authReducer(undefined, {type: "REGISTRATION_FAILED"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: true,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })

    it('should handle AUTHORIZATION_REQUEST', () => {
        expect(authReducer(undefined, {type: "AUTHORIZATION_REQUEST"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: true,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })

    it('should handle AUTHORIZATION_SUCCESS', () => {
        expect(authReducer(undefined, {
            type: "AUTHORIZATION_SUCCESS",
            email: "test",
            name: "test",
            accessToken: "test"
        })).toEqual({
            authChecked: true,
            loggedIn: true,
            isResetPasswordAvailable: false,
            registrationRequest: false,
            registrationFailed: false,
            currentLogin: "test",
            currentName: "test",
            authorizationRequest: false,
            authorizationFailed: false,
            accessToken: "test",
            getUserInfoRequest: false,
            getUserInfoFailed: false,
            updateUserInfoRequest: false,
            updateUserInfoFailed: false,
            logoutRequest: false,
            logoutFailed: false,
            resetPasswordRequest: false,
            resetPasswordFailed: false,
            recoveryCodeRequest: false,
            recoveryCodeFailed: false,
            refreshTokenRequest: false,
            refreshTokenFailed: false,
            refreshTokenSuccess: false,
        })
    })

    it('should handle AUTHORIZATION_FAILED', () => {
        expect(authReducer(undefined, {type: "AUTHORIZATION_FAILED"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: true,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle GET_USER_INFO_REQUEST', () => {
        expect(authReducer(undefined, {type: "GET_USER_INFO_REQUEST"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: true,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })

    it('should handle GET_USER_INFO_SUCCESS', () => {
        expect(authReducer(undefined, {
            type: "GET_USER_INFO_SUCCESS",
            name: "test",
            email: "test"
        })).toEqual({
            authChecked: false,
            loggedIn: !!localStorage.getItem("accessToken"),
            isResetPasswordAvailable: false,
            registrationRequest: false,
            registrationFailed: false,
            currentLogin: "test",
            currentName: "test",
            authorizationRequest: false,
            authorizationFailed: false,
            accessToken: null,
            getUserInfoRequest: false,
            getUserInfoFailed: false,
            updateUserInfoRequest: false,
            updateUserInfoFailed: false,
            logoutRequest: false,
            logoutFailed: false,
            resetPasswordRequest: false,
            resetPasswordFailed: false,
            recoveryCodeRequest: false,
            recoveryCodeFailed: false,
            refreshTokenRequest: false,
            refreshTokenFailed: false,
            refreshTokenSuccess: false,
        })
    })
    it('should handle GET_USER_INFO_FAILED', () => {
        expect(authReducer(undefined, {type: "GET_USER_INFO_FAILED"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: true,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should have UPDATE_USER_INFO_REQUEST', () => {
        expect(authReducer(undefined, {type: "UPDATE_USER_INFO_REQUEST"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: true,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle UPDATE_USER_INFO_SUCCESS', () => {
        expect(authReducer(undefined, {
            type: "UPDATE_USER_INFO_SUCCESS",
            name: "test",
            email: "test"
        })).toEqual({
            authChecked: false,
            loggedIn: !!localStorage.getItem("accessToken"),
            isResetPasswordAvailable: false,
            registrationRequest: false,
            registrationFailed: false,
            currentLogin: "test",
            currentName: "test",
            authorizationRequest: false,
            authorizationFailed: false,
            accessToken: null,
            getUserInfoRequest: false,
            getUserInfoFailed: false,
            updateUserInfoRequest: false,
            updateUserInfoFailed: false,
            logoutRequest: false,
            logoutFailed: false,
            resetPasswordRequest: false,
            resetPasswordFailed: false,
            recoveryCodeRequest: false,
            recoveryCodeFailed: false,
            refreshTokenRequest: false,
            refreshTokenFailed: false,
            refreshTokenSuccess: false,
        })
    })
    it('should handle UPDATE_USER_INFO_FAILED', () => {
        expect(authReducer(undefined, {type: "UPDATE_USER_INFO_FAILED"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: true,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle LOGOUT_REQUEST', () => {
        expect(authReducer(undefined, {type: "LOGOUT_REQUEST"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: true,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle LOGOUT_SUCCESS', () => {
        expect(authReducer(undefined, {type: "LOGOUT_SUCCESS"}))
            .toEqual({
                authChecked: false,
                loggedIn: false,
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle LOGOUT_FAILED', () => {
        expect(authReducer(undefined, {type: "LOGOUT_FAILED"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: true,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle RESET_PASSWORD_REQUEST', () => {
        expect(authReducer(undefined, {type: "RESET_PASSWORD_REQUEST"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: true,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle RESET_PASSWORD_SUCCESS', () => {
        expect(authReducer(undefined, {type: "RESET_PASSWORD_SUCCESS"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle RESET_PASSWORD_FAILED', () => {
        expect(authReducer(undefined, {type: "RESET_PASSWORD_FAILED"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: true,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle RECOVERY_CODE_REQUEST', () => {
        expect(authReducer(undefined, {type: "RECOVERY_CODE_REQUEST"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: true,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle RECOVERY_CODE_SUCCESS', () => {
        expect(authReducer(undefined, {type: "RECOVERY_CODE_SUCCESS"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: true,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle RECOVERY_CODE_FAILED', () => {
        expect(authReducer(undefined, {type: "RECOVERY_CODE_FAILED"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: true,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle REFRESH_TOKEN_REQUEST', () => {
        expect(authReducer(undefined, {type: "REFRESH_TOKEN_REQUEST"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: true,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
    it('should handle REFRESH_TOKEN_FAILED', () => {
        expect(authReducer(undefined, {type: "REFRESH_TOKEN_FAILED"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: true,
                refreshTokenSuccess: false,
            })
    })
    it('should handle REFRESH_TOKEN_SUCCESS', () => {
        expect(authReducer(undefined, {type: "REFRESH_TOKEN_SUCCESS"}))
            .toEqual({
                authChecked: false,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: true,
            })
    })
    it('should handle AUTH_CHECKED', () => {
        expect(authReducer(undefined, {type: "AUTH_CHECKED"}))
            .toEqual({
                authChecked: true,
                loggedIn: !!localStorage.getItem("accessToken"),
                isResetPasswordAvailable: false,
                registrationRequest: false,
                registrationFailed: false,
                currentLogin: "",
                currentName: "",
                authorizationRequest: false,
                authorizationFailed: false,
                accessToken: null,
                getUserInfoRequest: false,
                getUserInfoFailed: false,
                updateUserInfoRequest: false,
                updateUserInfoFailed: false,
                logoutRequest: false,
                logoutFailed: false,
                resetPasswordRequest: false,
                resetPasswordFailed: false,
                recoveryCodeRequest: false,
                recoveryCodeFailed: false,
                refreshTokenRequest: false,
                refreshTokenFailed: false,
                refreshTokenSuccess: false,
            })
    })
})